AutoSetOfflineMatch: true
BarterSchemeAutoFill: true
BarterSchemeAutoFillPersist: true
BossSpawnChance: true
BotSettingsLoad: true
BotTemplateLimit: true
BringBackInsuranceScreen: true
CoreDifficulty: true
DisableReadyButtonOnFirstScreen: true
DisableReadyButtonOnSelectLocation: true
DisableScavMode: true
EndByTimer: true
ExperienceGainFix: true
LoadBotDifficultyFromServer: true
LoadBotTemplatesFromServer: false
LoadOfflineRaidScreen: false
MaxBotCap: true
NoFilters: false
OfflineSaveProfile: true
OfflineSpawnPoint: true
OldStreamerMode: false
RemoveAddOfferButton_Awake: true
RemoveAddOfferButton_Call: true
RemoveUsedBotProfile: true
ReplaceInMainMenuController: true
ReplaceInPlayer: true
ScavExfilFix: false
ScavPrefabLoad: false
ScavProfileLoad: false
ScavSpawnPoint: false
SpawnPmc: true
SpawnRandomizationMod: true
TinnitusFix: false
UnlockItem24CharId: true
UpdateDogtagOnKill: true
