BeaconPatch: true
BossSpawnChancePatch: true
BotDifficultyPatch: true
BotStationaryWeaponPatch: true
BotTemplateLimitPatch: true
CoreDifficultyPatch: true
DogtagPatch: true
EndByTimerPatch: true
ExperienceGainPatch: true
GetNewBotTemplatesPatch: true
InsuranceScreenPatch: true
LoadOfflineRaidScreenPatch: true
MainMenuControllerPatch: true
MatchmakerOfflineRaidPatch: true
MatchMakerSelectionLocationScreenPatch: true
OfflineLootPatch: true
OfflineSaveProfilePatch: true
OfflineSpawnPointPatch: true
OnDeadPatch: true
OnShellEjectEventPatch: true
PlayerPatch: true
RemoveUsedBotProfilePatch: true
ScavExfilPatch: true
ScavPrefabLoadPatch: true
ScavProfileLoadPatch: true
ScavSpawnPointPatch: false
SingleModeJamPatch: true
SpawnPmcPatch: true
SpawnRandomizationPatch: true
WeaponDurabilityPatch: true
