stages:
  - lint

.lint-job: &lint-job
  image: python:3.10-slim
  stage: lint
  interruptible: true
  cache:
    - key:
        files:
          - poetry.lock
      paths:
        - .cache/pip
        - .venv
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  only:
    changes:
      - src/**/*
      - tests/**/*

  before_script:
    - export PYTHONPATH=$PYTHONPATH:./src
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install

black:
  <<: *lint-job
  script:
    - poetry run black . --check

isort:
  <<: *lint-job
  script:
    - poetry run isort . --check

flake8:
  <<: *lint-job
  script:
    - poetry run flake8

pytest:
  <<: *lint-job
  script:
    - poetry run coverage run
    - poetry run coverage report
    - poetry run coverage xml
  coverage: "/^TOTAL.*\s(\d+\.\d+)\%/"
  artifacts:
    reports:
      cobertura: coverage.xml

mypy:
  <<: *lint-job
  script:
    - poetry run mypy .
