stages:
  - lint

.lint-job: &lint-job
  image: python:3.10-slim
  stage: lint
  cache:
    - key:
        files:
          - poetry.lock
      paths:
        - .cache/pip
        - .venv

  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install

black:
  <<: *lint-job
  script:
    - poetry run black . --check

isort:
  <<: *lint-job
  script:
    - poetry run isort . --check

pytest:
  <<: *lint-job
  script:
    - poetry run pytest

mypy:
  <<: *lint-job
  script:
    - poetry run mypy .
