stages:
  - lint
  - build

.lint-job: &lint-job
  image: python:3.10-slim
  stage: lint
  cache:
    - key:
        files:
          - poetry.lock
      paths:
        - .cache/pip
        - .venv
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  before_script:
    - export PYTHONPATH=$PYTHONPATH:./src
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install

black:
  <<: *lint-job
  script:
    - poetry run black . --check

isort:
  <<: *lint-job
  script:
    - poetry run isort . --check

flake8:
  <<: *lint-job
  script:
    - poetry run flake8

pytest:
  <<: *lint-job
  script:
    - poetry run pytest

mypy:
  <<: *lint-job
  script:
    - poetry run mypy .

build:
  <<: *lint-job
  stage: build
  script:
    - pip install pyinstaller
    - pyinstaller main.spec --onefile
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
